# Generated by Django 4.1 on 2023-11-02 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biologist',
            fields=[
                ('ID_bio', models.AutoField(primary_key=True, serialize=False)),
                ('firstname_bio', models.CharField(max_length=255)),
                ('lastname_bio', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID_patient', models.AutoField(primary_key=True, serialize=False)),
                ('firstname_patient', models.CharField(max_length=50)),
                ('lastname_patient', models.CharField(max_length=50)),
                ('street_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('street_name', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Postal code must be 5 digits')])),
                ('city_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone_nb', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('insured', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('ID_test', models.AutoField(primary_key=True, serialize=False)),
                ('name_test', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.biologist')),
            ],
            options={
                'unique_together': {('ID_test', 'ID_bio')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('ID_bill', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_red', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.patient')),
            ],
            options={
                'unique_together': {('ID_bill', 'ID_patient')},
            },
        ),

        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateField()),
                ('date_bill', models.DateField()),
                ('ID_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.bill')),
                ('ID_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.test')),
            ],
            options={
                'unique_together': {('ID_bill', 'ID_test')},
            },
        ),
    ]
