# Generated by Django 4.1 on 2023-11-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test_center_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_results', models.CharField(max_length=255)),
                ('date_results', models.DateField()),
                ('ID_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.patient')),
                ('ID_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_test_center_app.test')),
            ],
            options={
                'unique_together': {('ID_patient', 'ID_test')},
            },
        ),
    ]
