# Generated by Django 4.1 on 2023-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_test_center_app', '0002_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insured',
            field=models.IntegerField(choices=[(0, 'Not Insured'), (1, 'Insured')]),
        ),
    ]
